opam-version: "2.0"
name: "irmin-website"
synopsis: "Public homepage of Irmin"
license: "ISC"
maintainer: "Craig Ferguson <me@craigfe.io>"
authors: "Craig Ferguson <me@craigfe.io>"
homepage: "https://github.com/tarides/irmin.org"
bug-reports: "https://github.com/tarides/irmin.org/issues"
depends: [
  "ocaml" {>= "5.1.0"}
  "dune" {>= "3.5.0"}
  "irmin" {"dev" & with-test}
  "irmin-cli" {"dev" & with-test}
  "digestif" {>= "1.0.0"}
  "mdx" {>= "2.0.0"}
  "lwt" {with-test}
]
build: [
  ["dune" "subst"] {pinned}
  ["dune" "build" "-p" name "-j" jobs]
  ["dune" "runtest" "-p" name] {with-test}
]
dev-repo: "git+https://github.com/tarides/irmin.org.git"
pin-depends: [
  ["irmin.dev" "git+https://github.com/mirage/irmin#a76dfaa3012713b58d4b9e471d471f1caf5e89bf"]
  ["irmin-git.dev" "git+https://github.com/mirage/irmin#a76dfaa3012713b58d4b9e471d471f1caf5e89bf"]
  ["irmin-server.dev" "git+https://github.com/mirage/irmin#a76dfaa3012713b58d4b9e471d471f1caf5e89bf"]
  ["irmin-client.dev" "git+https://github.com/mirage/irmin#a76dfaa3012713b58d4b9e471d471f1caf5e89bf"]
  ["irmin-pack.dev" "git+https://github.com/mirage/irmin#a76dfaa3012713b58d4b9e471d471f1caf5e89bf"]
  ["irmin-tezos.dev" "git+https://github.com/mirage/irmin#a76dfaa3012713b58d4b9e471d471f1caf5e89bf"]
  ["irmin-graphql.dev" "git+https://github.com/mirage/irmin#a76dfaa3012713b58d4b9e471d471f1caf5e89bf"]
  ["irmin-cli.dev" "git+https://github.com/mirage/irmin#a76dfaa3012713b58d4b9e471d471f1caf5e89bf"]
  ["ppx_irmin.dev" "git+https://github.com/mirage/irmin#a76dfaa3012713b58d4b9e471d471f1caf5e89bf"]
  [ "irmin-watcher.dev" "git+https://github.com/patricoferris/irmin-watcher#d0e92b4ba5631b5f4dc0f3c00d97e79542dba45d" ]
  [ "index.dev"    "git+https://github.com/mirage/index#6e84bed48db8ab53a09926b45d899815c30f2b39"     ]

]
